# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FilmlerApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'Alamofire', '~> 5.4.4'
  pod 'RxSwift', '~> 6.2.0'
  pod 'RxCocoa', '~> 6.2.0'
  pod 'Kingfisher'

  # Pods for FilmlerApp

end
